
<ElevatorCheckCall>:
    size_hint_y: None
    height: '150sp'
    source:root.imgsource
    on_press:root.presscall()
    on_release:root.releasecall()

    size_hint_x:1
    canvas.before:
        Color:
            rgba: root.colorborder
        Line:
            width: 1
            points: self.x, self.y, self.x+ self.width, self.y
    canvas:
        Color:
            rgba: self.colorback
        Rectangle:

            pos: self.pos
            size: self.size

<ElevatorAvailable>:
    size_hint_y: None
    height: '150sp'
    canvas.before:
        Color:
            rgba: root.colorborder
        Line:
            width: 1
            points: self.x, self.y, self.x+ self.width, self.y
    canvas:
        Color:
            rgba: self.colorback if self.Av == 1 else self.colorbackforbid
        Rectangle:

            pos: self.pos
            size: self.size
    on_active:root.updateAv(self.active)

<ElevatorBoxs>:
    size_hint_y: None
    height: '150sp'

    canvas.before:
        Color:
            rgba: root.colorborder
        Line:
            width: 1
            points: self.x, self.y, self.x+ self.width+self.add, self.y
    canvas:
        Color:
            rgba: self.colorback if self.state == 1 else self.colorbackforbid
        Rectangle:

            pos: self.pos
            size: self.size
    AnchorLayout:
        center:self.parent.center
        anchor_x: 'center'
        anchor_y: 'center'
        Image:
            source:root.source
            opacity:int(root.show)
            size_hint_x:root.sizehintx





<ElevatorDown>:
    cols:4
    spacing:10
    box: box
    box2: box2
    box3: box3
    boxcall:boxcall
    ScrollView:
        do_scroll_y:False
        scroll_y:root.scrollvalue
        size_hint_x:0.5
        GridLayout:
            cols:1
            size_hint_y:  None
            height: self.minimum_height
            id:boxcall
    ScrollView:
        do_scroll_y:False
        scroll_y:root.scrollvalue
        size_hint_x:0.65

        GridLayout:
            cols:1
            id:box
            size_hint_y:  None
            height: self.minimum_height
            id:box


    ScrollView:
        do_scroll_y:False
        scroll_y:root.scrollvalue
        size_hint_x:0.45
        GridLayout:
            cols:1
            id:box2
            size_hint_y:  None
            height: self.minimum_height


    ScrollView:
        do_scroll_y:False
        scroll_y:root.scrollvalue
        GridLayout:
            id:box3
            cols:1
            size_hint_y:  None
            height: self.minimum_height









<ElevatorUPRight>:
    rows:3
    BoxLayout:
        orientation:'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: root.colorborder
                Line:
                    width: 1
                    rectangle: self.x, self.y, self.width, self.height
            canvas:
                Color:
                    rgba: root.colorback
                Rectangle:
                    pos: self.pos
                    size: self.size
            BoxLayout:
                center:self.parent.center
                orientation:'horizontal'
                AnchorLayout:
                    size_hint_x:0.2
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source:'index_elevator.png'


                AnchorLayout:
                    anchor_x: 'right'
                    anchor_y: 'center'
                    Label:
                        id:IndexElev
                        font_name:'times.ttf'
                        font_size:self.width/4
                        text: root.indexName




        Label:
            canvas.before:
                Color:
                    rgba: root.colorborder
                Line:
                    width: 1
                    rectangle: self.x, self.y, self.width, self.height
            canvas:
                Color:
                    rgba: root.colorback
                Rectangle:
                    pos: self.pos
                    size: self.size
            BoxLayout:
                center:self.parent.center
                orientation:'horizontal'
                AnchorLayout:
                    size_hint_x:0.2
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source:'human2.png'
                        size_hint_x:1
                AnchorLayout:
                    anchor_x: 'right'
                    anchor_y: 'center'
                    Label:
                        font_name:'times.ttf'
                        font_size:self.width/4
                        text: "{:.0f}".format(root.InCarPercent)+"%"
        Label:
            canvas.before:
                Color:
                    rgba: root.colorborder
                Line:
                    width: 1
                    rectangle: self.x, self.y, self.width, self.height
            canvas:
                Color:
                    rgba: root.colorback
                Rectangle:
                    pos: self.pos
                    size: self.size
            BoxLayout:
                center:self.parent.center
                orientation:'horizontal'
                AnchorLayout:
                    size_hint_x:0.2
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source:'waiting2.png'
                        size_hint_x:1
                AnchorLayout:
                    anchor_x: 'right'
                    anchor_y: 'center'
                    Label:
                        font_name:'times.ttf'
                        font_size:self.width/4
                        text: "{:.0f}".format(root.NumberRequest)


<ElevatorUP>:
    rows:5

    canvas.before:
        Color:
            rgba: root.colorborder
        Line:
            width: 1
            rectangle: self.x, self.y, self.width, self.height

    GridLayout:
        size_hint_y:0.4
        cols:2
        canvas.before:
            Color:
                rgba: root.colorborder
            Line:
                width: 1
                rectangle: self.x, self.y, self.width, self.height
        canvas:
            Color:
                rgba: 1,1,1,0
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            canvas.before:
                Color:
                    rgba: root.colorborder
                Line:
                    width: 1
                    rectangle: self.x, self.y, self.width, self.height
            canvas:
                Color:
                    rgba: 1,1,1,0
                Rectangle:
                    pos: self.pos
                    size: self.size
            text:root.curFloor
            font_name:"Seven Segment.ttf"
            font_size:self.height*0.9
        SettingElevator:
            size_hint_x:0.3
            index:root.index
            elevGrp:root.elevGrp
            source:"setting_elevator.png"
            on_release:self.Select_Config()


    GridLayout:
        size_hint_y:1.2
        cols:2
        canvas.before:
            Color:
                rgba: root.colorborder
            Line:
                width: 1
                rectangle: self.x, self.y, self.width, self.height
        BoxLayout:
            canvas.before:
                Color:
                    rgba: root.colorborder
                Line:
                    width: 1
                    rectangle: self.x, self.y, self.width, self.height
            canvas:
                Color:
                    rgba: root.colorback
                Rectangle:
                    pos: self.pos
                    size: self.size
            orientation:'vertical'
            size_hint_x:0.5
            BoxLayout:
                orientation:'horizontal'
                AnchorLayout:
                    size_hint_x:1.2
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source:root.QualitySource
                        center:int(self.center_x),int(self.center_y)
                        size_hint_y:0.7
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Label:
                        font_name:'times.ttf'
                        font_size:self.width/2.5
                        text:root.State
                        color:root.colorwhite if root.AvailElev == 1 else root.colorerror
                        size_hint_y:1




            AnchorLayout:
                anchor_x: 'center'
                anchor_y: 'center'
                Image:
                    id:AvailElev
                    source:root.SourceAvailElev
                    size_hint_y:1 if root.vip==1 else 0.8



        ElevatorUPRight:
            index:root.index
            elevGrp:root.elevGrp













<Elevator>:
    rows:2
    GridLayout:
        size_hint_y:0.2
        cols:2
        ElevatorUP:
            index:root.index
            elevGrp:root.elevGrp
        GridLayout:
            rows:6
            canvas.before:
                Color:
                    rgba: root.colorborder
                Line:
                    width: 1
                    rectangle: self.x, self.y, self.width, self.height

            size_hint_x:0.15
            Label:
                size_hint_y:0.1
            Image:
                source:'Dir_Down.png'

            Label:
                text:root.Command[0]
            Label:
                text:root.Command[1]
            Label:
                text:root.Command[2]
            Label:
                text:root.Command[3]
    ElevatorDown:
        index:root.index



<PopupWindowConfig>:
    cols:3
    padding:30

    GridLayout:
        rows:4
        padding:30
        spacing:30
        canvas.before:
            Color:
                rgba: root.colorwhite if root.disable==0 else root.colordisable
            Line:
                width: 1.5
                rounded_rectangle: self.x, self.y, self.width, self.height,10
        GridLayout:
            size_hint_y:0.2
            padding:10
            spacing:10

            cols:8
            Label:
                size_hint_x:0.5
            TextInput:
                hint_text:"Elevator Index Name"
                id:ElevIndex
            TextInput:
                hint_text:"Elevator Capacity"
                id:ElevCapacity
            Button:
                text:"Config Setup"
                on_press:root.Select_Setup()
            ConfigPush:
                vip:True
                elevatorindex:root.elevatorindex

            ConfigPush:
                learning:True
                elevatorindex:root.elevatorindex
            Label:
                size_hint_x:0.5
        GridLayout:
            rows:2
            size_hint_y:0.4
            Label:
                size_hint_y:0.1
                text:"Location Elevator"
                font_size:self.height*1.5
            GridLayout:
                cols:3

                Label:
                    id:ee
                LocationPanel:

                    padding:10
                    spacing:10
                    rows:2
                    elevatorindex:root.elevatorindex
                Label:
                    id:ff



        GridLayout:
            rows:2
            Label:
                size_hint_y:0.04
                text:"Seven Segment Available"
                font_size:self.height*1.5
            GridLayout:
                cols:3
                Label:
                    size_hint_x:0.8

                SevenSegmentPush:
                    cols:2
                    elevatorindex:root.elevatorindex
                Label:
                    size_hint_x:0.8






<ConfigPush>:
    canvas.before:
        Color:
            rgba: root.colorwhite if root.disable==0 else root.colordisable
        Line:
            width: 1.5
            rounded_rectangle: self.x, self.y, self.width, self.height,10
    source:"raw.png"
    on_press:self.Select_Button()
    Label:
        text:root.label
        font_size:self.height*0.2
        center:root.center
        color:root.colordisable if root.disable==1 else root.colorwhite
<SevenSegmentPush>:
    padding:20
    spacing:10
    background_color: root.colorblack




<SevenSegmentButton>:

    on_press:self.Select_Button()
    canvas.before:
        Color:
            rgba: root.colorwhite if root.disable==0 else root.colordisable
        Line:
            width: 1.5
            rounded_rectangle: self.x, self.y, self.width, self.height,10
    source:"raw.png"
    Label:
        text:root.label
        font_size:self.height*0.25
        center:root.center
        color:root.colordisable if root.disable==1 else root.colorwhite



<LocationButton>:
    canvas.before:
        Color:
            rgba: root.colorwhite if root.disable==0 else root.colordisable
        Line:
            width: 1.5
            rounded_rectangle: self.x, self.y, self.width, self.height,5
    source:"raw.png"
    on_press:self.Select_Button()
    Label:
        text:root.label
        font_size:self.height*0.4
        center:root.center
        color:root.colordisable if root.disable==1 else root.colorwhite

